--
-- PostgreSQL database dump
--

\restrict x4AM3cXuAQXl2nvpYw8IOTY8Mdtt8lPeJXB67V2rz5rWVGuEmr3bfosIgS8iH8x

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-03-16 11:13:58

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: biblioteca_app
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO biblioteca_app;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: autores; Type: TABLE; Schema: public; Owner: biblioteca_app
--

CREATE TABLE public.autores (
    cedula character varying(20) NOT NULL,
    nacionalidad character varying(80) NOT NULL,
    nombre_completo character varying(120) NOT NULL
);


ALTER TABLE public.autores OWNER TO biblioteca_app;

--
-- TOC entry 220 (class 1259 OID 16397)
-- Name: libros; Type: TABLE; Schema: public; Owner: biblioteca_app
--

CREATE TABLE public.libros (
    isbn character varying(20) NOT NULL,
    anio_publicacion integer NOT NULL,
    editorial character varying(100) NOT NULL,
    genero character varying(50) NOT NULL,
    titulo character varying(150) NOT NULL,
    autor_cedula character varying(20) NOT NULL
);


ALTER TABLE public.libros OWNER TO biblioteca_app;

--
-- TOC entry 222 (class 1259 OID 16409)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: biblioteca_app
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    tipo character varying(20) NOT NULL,
    user_name character varying(50) NOT NULL,
    CONSTRAINT usuarios_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ADMIN'::character varying, 'EMPLEADO'::character varying])::text[])))
);


ALTER TABLE public.usuarios OWNER TO biblioteca_app;

--
-- TOC entry 221 (class 1259 OID 16408)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: biblioteca_app
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5021 (class 0 OID 16389)
-- Dependencies: 219
-- Data for Name: autores; Type: TABLE DATA; Schema: public; Owner: biblioteca_app
--

COPY public.autores (cedula, nacionalidad, nombre_completo) FROM stdin;
12345678	Colombiana	Gabriel Garcia Marquez
87654321	Español	Miguel de Servantes Saavedra
\.


--
-- TOC entry 5022 (class 0 OID 16397)
-- Dependencies: 220
-- Data for Name: libros; Type: TABLE DATA; Schema: public; Owner: biblioteca_app
--

COPY public.libros (isbn, anio_publicacion, editorial, genero, titulo, autor_cedula) FROM stdin;
9780307474728	1967	Sudamericana	Novela	Cien años de soledad	12345678
9781589770034	1605	Panamericana	Novela	Don Quijote de la mancha	87654321
9788497592451	1985	Diana	Novela	El amor en tiempos de colera	12345678
\.


--
-- TOC entry 5024 (class 0 OID 16409)
-- Dependencies: 222
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: biblioteca_app
--

COPY public.usuarios (id, password, tipo, user_name) FROM stdin;
1	$2a$10$9gEQXnkgsvK5g.tuQ6xVA.VbVtm80HYs5HNhiuqynp/w0ASHOafRK	ADMIN	admin
2	$2a$10$Hc9zR94iLjJg5g7uQYi69ONuOI1OVkIUhoSxRn9Fv3C7bA/ObL0KO	EMPLEADO	empleado1
4	$2a$10$OHR3uZ/kdP/vlKyMwLuX9eeljGEhH3YZavXZAruG04G/ACMJFqxDW	EMPLEADO	mateo
\.


--
-- TOC entry 5030 (class 0 OID 0)
-- Dependencies: 221
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: biblioteca_app
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 4, true);


--
-- TOC entry 4866 (class 2606 OID 16396)
-- Name: autores autores_pkey; Type: CONSTRAINT; Schema: public; Owner: biblioteca_app
--

ALTER TABLE ONLY public.autores
    ADD CONSTRAINT autores_pkey PRIMARY KEY (cedula);


--
-- TOC entry 4868 (class 2606 OID 16407)
-- Name: libros libros_pkey; Type: CONSTRAINT; Schema: public; Owner: biblioteca_app
--

ALTER TABLE ONLY public.libros
    ADD CONSTRAINT libros_pkey PRIMARY KEY (isbn);


--
-- TOC entry 4870 (class 2606 OID 16420)
-- Name: usuarios ukr9ksbmgwvokav9vgydstfdmws; Type: CONSTRAINT; Schema: public; Owner: biblioteca_app
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukr9ksbmgwvokav9vgydstfdmws UNIQUE (user_name);


--
-- TOC entry 4872 (class 2606 OID 16418)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: biblioteca_app
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 4873 (class 2606 OID 16421)
-- Name: libros fkhpi72ophrbu88w2cwr96151gc; Type: FK CONSTRAINT; Schema: public; Owner: biblioteca_app
--

ALTER TABLE ONLY public.libros
    ADD CONSTRAINT fkhpi72ophrbu88w2cwr96151gc FOREIGN KEY (autor_cedula) REFERENCES public.autores(cedula);


-- Completed on 2026-03-16 11:13:58

--
-- PostgreSQL database dump complete
--

\unrestrict x4AM3cXuAQXl2nvpYw8IOTY8Mdtt8lPeJXB67V2rz5rWVGuEmr3bfosIgS8iH8x

