spring.application.name=biblioteca
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca_db
spring.datasource.username=biblioteca_app
spring.datasource.password=Biblioteca2026*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=bXktc3VwZXItc2VjcmV0LWtleS1wYXJhLWp3dC1zaWduaW5nLTMydGVzLW1pbmltbw==
jwt.expiration=86400000

debug=true